shop/checkout/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'checkout'
urlpatterns = [
    path('', views.checkoutAddress, name="checkoutAddress"),
    path('payment/', views.processPayment, name="processPayment"),
    path('paymentAccepted/', views.orderFinished, name="orderFinished")
]

shop/listings/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.index, name='index'),
    path('listings/<int:id>', views.listing, name='listing'),
    path('search/', views.search, name="search_results"),
    path('quicksearch/', views.quick_search, name="quick_search"),
    path('category/<int:id>', views.category, name="category"),
    path('updateCart/', views.update_cart_item, name="update_cart_item"),
    path('cart/', views.cart_view, name="cart"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('listings.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('checkout/', include('checkout.urls')),
]

shop/listings/models.py
from datetime import datetime
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from checkout.models import CustomerInformation


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Listing(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.FloatField()
    image = models.ImageField(upload_to="static/listings/%y/%m/%d/", blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    slug = models.SlugField(null=True)

    def __str__(self) -> str:
        return self.name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(default=datetime.now())
    active = models.BooleanField(default=False)
    deviceId = models.CharField(max_length=250, null=True, blank=True)
    finished = models.BooleanField(default=False)
    delivery_address = models.ForeignKey(CustomerInformation, blank=True, null=True, on_delete=models.SET_NULL)

    def get_total(self):
        return sum(x.get_sum() for x in self.orderlisting_set.all())

    def __str__(self):
        if self.user:
            return self.user.username
        return self.deviceId


class OrderListing(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    is_active = models.BooleanField(default=True)

    def get_sum(self):
        return self.listing.price * self.quantity

    def __str__(self):
        return self.listing.name

shop/listings/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from .models import Listing, Category, Order, OrderListing
from django.http import JsonResponse
from django.core import serializers
from django.shortcuts import get_object_or_404, get_list_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages


# Create your views here.

def index(request):
    items = get_list_or_404(Listing.objects.all())
    categories = Category.objects.all()
    context = {'items': items, 'categories': categories}
    return render(request, 'listings/index.html', context)


def listing(request, id):
    item = get_object_or_404(Listing, pk=id)
    return render(request, 'listings/listing.html', {'item': item})


def search(request):
    q = request.GET.get("q")
    items = Listing.objects.filter(name__icontains=q.strip())
    if "lastSearch" not in request.session or request.session['lastSearch']:
        request.session["lastSearch"] = [q]
        request.session.modified = True
    else:
        last_searches = request.session.get("lastSearch")
        last_searches.insert(0, q)
        request.session["lastSearch"] = last_searches[:3]
    return render(request, 'listings/search.html', {'items': items})


def quick_search(request):
    amount = 3
    if request.is_ajax() and request.method == "GET":
        text = request.GET.get('currentWord', None)
        items = list(Listing.objects.filter(name__icontains=text.strip())[:amount].values())
        return JsonResponse({"items": items}, status=200)
    return redirect('listings:index')


def category(request, id):
    items = Listing.objects.filter(category_id=id)
    return render(request, 'listings/category.html', context={'items': items})


def cart_view(request):
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(user=request.user, finished=False)
    else:
        device = request.COOKIES['device']
        order, created = Order.objects.get_or_create(deviceId=device, finished=False)
    items = order.orderlisting_set.all()
    context = {'items': items, 'order': order}
    return render(request, 'listings/cart.html', context)


def update_cart_item(request):
    item_id = request.POST.get('item')
    action = request.POST.get('action')
    quantity = int(request.POST.get('quantity', 1))
    item = Listing.objects.get(id=item_id)
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(user=request.user, finished=False)
    else:
        device = request.COOKIES['device']
        order, created = Order.objects.get_or_create(deviceId=device, finished=False)

    orderItem, created = OrderListing.objects.get_or_create(listing=item, order=order)
    if action == "add":
        if not created:
            orderItem.quantity += quantity
    elif action == "delete":
        orderItem.quantity = 0
    else:
        # set
        orderItem.quantity = quantity
    orderItem.save()
    if orderItem.quantity <= 0:
        orderItem.delete()
    order.save()
    return JsonResponse({"output": "Done"}, status=200)

shop/templates/listings/cart.html
{% extends 'base.html' %} {% load static %}
{% block content %}


    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom-0">
                <h5 class="modal-title" id="exampleModalLabel">
                    Your Shopping Cart
                </h5>
            </div>
            <div class="modal-body">
                {% if items %}
                    <table class="table table-image">
                        <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Total</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in items %}
                            <tr>
                                <td class="w-25">
                                    <a href="{% url 'listings:listing' item.listing.id %}">
                                        <img class="cartImage" src="{{ item.listing.image.url }}"
                                             alt="Sheep">
                                    </a>
                                </td>
                                <td>{{ item.listing.name }}</td>
                                <td>{{ item.listing.price }} PLN</td>
                                <td class="qty"><input type="text" class="form-control setItemQuantityValue"
                                                       data-id="{{ item.listing.id }}"
                                                       id="input1" value="{{ item.quantity }}"></td>
                                <td>{{ item.get_sum }} PLN</td>
                                <td>
                                    <a data-id="{{ item.listing.id }}" class="btn btn-danger btn-sm deleteFromCart">
                                        <i class="fa fa-times">Delete</i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-end">
                        <h5>Total: <span class="price text-success">{{ order.get_total }} PLN</span></h5>
                    </div>
                {% else %}
                    <h1>There is no items in your cart</h1>
                {% endif %}


            </div>
            <div class="modal-footer border-top-0 d-flex justify-content-between">
                <a href="{% url 'listings:index' %}" type="button" class="btn btn-secondary"
                   data-dismiss="modal">Go back
                </a>
                <a href="{% url 'checkout:checkoutAddress' %}" type="button" class="btn btn-success">Checkout</a>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/listings/category.html
{% extends 'base.html' %} {% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                {% if items %}
                    {% for item in items %}
                        <div class="col-md-3 product-box py-3 border">
                            <img src="{{ item.image.url }}" width="200px" height="auto" alt="Zdjecie"/>
                            <p>{{ item.name }}</p>
                            <p>Cena: {{ item.price|floatformat:2}}</p>
                            <a role="button" class="btn btn-primary"
                               href="{% url 'listings:listing' item.id %}">Szczegoly</a>
                        </div>
                    {% endfor %}
                {% else %}
                    <h1>Nie ma wynikow</h1>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

shop/templates/listings/index.html
{% extends 'base.html' %} {% load static %} {% block content %}

    <div class="container-fluid">
        <div class="row col-12">
            <div class="col-md-2 m-0 p-0">
                <ul class="list-group list-group-flush">
                    {% if categories %}
                        {% for category in categories %}
                            <a href={% url 'listings:category' id=category.id %} class="text-decoration-none">
                                <li class="list-group-item ">
                                    {{ category.name }}
                                </li>
                            </a>
                        {% endfor %}
                    {% endif %}

                </ul>
            </div>
            <div class="col-md-10 text-center">
                <div class="container">
                    <div class="row col-md-12">
                        {% for item in items %}
                            <div class="col-md-3 product-box py-3 border">
                                <img src="{{ item.image.url }}" width="200px" height="auto" alt="Zdjecie"/>
                                <p>{{ item.name }}</p>
                                <p>Cena: {{ item.price|floatformat:2}}</p>
                                <a role="button" class="btn btn-primary"
                                   href="{% url 'listings:listing' item.id %}">Szczegoly</a>
                                <button type="button" class="btn btn-primary addToCart my-2" data-bs-toggle="modal"
                                        data-bs-target="#exampleModal"
                                        data-id="{{ item.id }}">Add to Cart
                                </button>

                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Dodano do koszyka</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-footer">
                            <a href="{% url 'listings:cart' %}" type="button" class="btn btn-secondary"
                               data-bs-dismiss="modal">Wroc do zakupow
                            </a>
                            <a href="{% url 'listings:cart' %}" type="button" class="btn btn-primary">Idz do koszyka</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

shop/templates/listings/listing.html
{% extends 'base.html' %} {% load static %} {% block content %}
    <div class="container-fluid m3">
        <div class="row">
            <div class="col-sm-5">
                <img src="{{ item.image.url }}" class="mx-auto rounded d-block border" width="300px" height="auto"
                     alt="Zdjecie"/>
            </div>
            <div class="col-lg-7">
                <h1>{{ item.name }}</h1>
                <p>Cena: {{ item.price }}</p>
                <img class="add_to_favorite" data-id="{{ item.id }}" src="{% static 'img/favorite.png' %}" width="50px"
                     height="50px" alt="">
                <button type="button" class="btn btn-primary addToCart my-2" data-bs-toggle="modal"
                        data-bs-target="#exampleModal"
                        data-id="{{ item.id }}">Add to Cart
                </button>
            </div>

            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Dodano do koszyka</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>

                        <div class="modal-footer">
                            <a href="{% url 'listings:cart' %}" type="button" class="btn btn-secondary"
                               data-bs-dismiss="modal">Wroc do zakupow
                            </a>
                            <a href="{% url 'listings:cart' %}" type="button" class="btn btn-primary">Idz do koszyka</a>
                        </div>
                    </div>
                </div>
            </div>
            <hr/>
        </div>
    </div>
    <div class="container-fluid m3">
        <div class="container m3 border text-center">
            <h2>Opis</h2>
            <p>{{ item.description }}</p>

        </div>
    </div>

{% endblock %}

shop/templates/listings/search.html
{% extends 'base.html' %} {% load static %} 
{% block content %}
<div class="container-fluid">
    <div class="container">
        <div class="row">
        {% if items %}
                {% for item in items%}
                    <div class="col-md">
                        <img src = "{{item.image.url}}" width="200px" height="auto" alt = "Zdjecie"></img>
                        <p>{{item.name}}</p>
                        <p>Cena: {{item.price|floatformat:2}}</p>
                        <a role="button" class="btn btn-primary" href="{% url 'listings:listing' item.id %}">Szczegoly</a>
                    </div>
                {% endfor%}
        {% else %}
            <h1>Nie ma wynikow</h1>
        {% endif %}

        </div>
    </div>
</div>
{% endblock %}