shop/checkout/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'checkout'
urlpatterns = [
    path('', views.checkoutAddress, name="checkoutAddress"),
    path('payment/', views.processPayment, name="processPayment"),
    path('paymentAccepted/', views.orderFinished, name="orderFinished")
]

shop/listings/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.index, name='index'),
    path('listings/<int:id>', views.listing, name='listing'),
    path('search/', views.search, name="search_results"),
    path('quicksearch/', views.quick_search, name="quick_search"),
    path('category/<int:id>', views.category, name="category"),
    path('updateCart/', views.update_cart_item, name="update_cart_item"),
    path('cart/', views.cart_view, name="cart"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('listings.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('checkout/', include('checkout.urls')),
]

shop/checkout/forms.py
from django import forms
from .models import CustomerInformation


class AddressForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['addressName'].label = 'Nazwa adresu'

    class Meta:
        model = CustomerInformation
        fields = ('id', 'addressName', 'phone_number', 'email', 'street', 'city', 'zip_code', 'default')

    def save(self, commit=True, *args, **kwargs):
        user = kwargs.get('user', False)
        if user:
            self.instance.user = kwargs['user']
        return super().save(commit=commit)

shop/templates/checkout/checkoutdata.html
{% extends 'base.html' %} {% load static %} {% block content %}{% load crispy_forms_tags %}

    <div class="container py-5">
        <h1>Address</h1>
        <form action="" method="GET">
            <label for="choice">Chcesz uzyc zapisanego adresu?</label>
            <select name="choice">
                {% for address in addresses %}
                    <option value="{{ address.id }}"
                            {% if request.GET.choice == address.id|stringformat:"i" %}selected{% endif %}>
                        {{ address.addressName }}
                    </option>
                {% endfor %}
                <option value="new" {% if request.GET.choice == "new" %}selected{% endif %}>Create new</option>
                <input type="submit" value="Change">
            </select>
        </form>
        <form method="POST">
            {% csrf_token %}
            <input name="id" type="hidden" value="{{ id }}">
            {{ address_form|crispy }}
            <button class="btn btn-primary" type="submit">Dalej</button>
        </form>
    </div>
{% endblock %}

shop/templates/checkout/paymentFinished.html
{% extends 'base.html' %} {% load static %} {% block content %}{% load crispy_forms_tags %}
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom-0">
                <h5 class="modal-title" id="exampleModalLabel">
                    Produkty zakupione!
                </h5>
            </div>
            <div class="modal-body">
                <table class="table table-image">
                    <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Product</th>
                        <th scope="col">Price</th>
                        <th scope="col">Qty</th>
                        <th scope="col">Price Total</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td class="w-25">
                                <a href="{% url 'listings:listing' item.listing.id %}">
                                    <img class="cartImage" src="{{ item.listing.image.url }}"
                                         alt="Sheep"></a></td>

                            <td>{{ item.listing.name }}</td>
                            <td>{{ item.listing.price }} PLN</td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.get_sum }} PLN</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="d-flex justify-content-end">
                    <h5>Total: <span class="price text-success">{{ order.get_total }} PLN</span></h5>
                </div>
                <table class="table table-image">
                    <thead>
                    <tr>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Email</th>
                        <th scope="col">Street</th>
                        <th scope="col">City</th>
                        <th scope="col">Zip-code</th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{{ address.phone_number }}</td>
                        <td>{{ address.email }}</td>
                        <td>{{ address.street }}</td>
                        <td>{{ address.city }}</td>
                        <td>{{ address.zip_code }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/checkout/processPayment.html
{% extends 'base.html' %} {% load static %} {% block content %}{% load crispy_forms_tags %}
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom-0">
                <h5 class="modal-title" id="exampleModalLabel">
                    Twoje zakupy
                </h5>
            </div>
            <div class="modal-body">
                {% if items %}
                    <table class="table table-image">
                        <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Price Total</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in items %}
                            <tr>
                                <td class="w-25">
                                    <a href="{% url 'listings:listing' item.listing.id %}">
                                        <img class="cartImage" src="{{ item.listing.image.url }}"
                                             alt="Sheep"></a></td>

                                <td>{{ item.listing.name }}</td>
                                <td>{{ item.listing.price }} PLN</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.get_sum }} PLN</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-end">
                        <h5>Total: <span class="price text-success">{{ order.get_total }} PLN</span></h5>
                    </div>
                {% endif %}


            </div>
            <div class="modal-footer border-top-0 d-flex justify-content-between">
                <a href="{% url 'listings:index' %}" type="button" class="btn btn-secondary"
                   data-dismiss="modal">Go back
                </a>
                <form action="{% url 'checkout:orderFinished' %}">
                    <button class="btn btn-success pay" type="button">
                        <span id="spinner" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"
                              hidden></span>
                        <span class="sr-only">Pay</span>
                    </button>
                    <input type="submit" value="" class="redirect" hidden>
                </form>

            </div>
        </div>
    </div>

{% endblock %}