shop/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_request, name='login'),
    path('register/', views.register_request, name="register"),
    path('information/', views.account_info, name="acc_info"),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='accounts/loggedout.html',
    ), name="logout"),
    path('favorite/', views.favoriteListings, name="favorite"),
    path('deleteFavorite/', views.deleteFavorite, name="deleteFavorite"),
    path('addFavorite/', views.addFavorite, name="addFavorite"),
]

shop/listings/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.index, name='index'),
    path('listings/<int:id>', views.listing, name='listing'),
    path('search/', views.search, name="search_results"),
    path('quicksearch/', views.quick_search, name="quick_search"),
    path('category/<int:id>', views.category, name="category"),
    path('updateCart/', views.update_cart_item, name="update_cart_item"),
    path('cart/', views.cart_view, name="cart"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('listings.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('checkout/', include('checkout.urls')),
]

shop/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from listings.models import Listing


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listings = models.ManyToManyField(Listing)

shop/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

shop/accounts/views.py
from django.contrib.auth.signals import user_logged_in
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Favorite
from listings.models import Listing


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("listings:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request, template_name="accounts/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("listings:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request, template_name="accounts/login.html", context={"login_form": form})


@login_required(login_url='/accounts/login/')
def account_info(request):
    return render(request, template_name="accounts/information.html")


def logout(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("listings:index")


@login_required(login_url='/accounts/login/')
def favoriteListings(request):
    user = request.user
    listings, created = Favorite.objects.get_or_create(user=user)
    context = {
        'listings': listings.listings.all(),
    }
    return render(request, template_name="accounts/favorite.html", context=context)


def deleteFavorite(request):
    item_id = request.POST.get('item')
    print(item_id)
    favorite = Favorite.objects.get(user=request.user)
    listing = Listing.objects.get(id=item_id)
    favorite.listings.remove(listing)
    favorite.save()
    return JsonResponse({'output': 'success'}, status=200)


def addFavorite(request):
    item_id = request.POST.get('item')
    favorite = Favorite.objects.get(user=request.user)
    listing = Listing.objects.get(id=item_id)
    messages.info(request, 'Dodano do ulubionych')
    favorite.listings.add(listing)
    favorite.save()
    return JsonResponse({'output': 'success'}, status=200)

shop/templates/accounts/favorite.html
{% extends 'base.html' %} {% load static %} {% block content %}
    <div class="container">
        <div class="row">
            {% if listings %}
                {% for item in listings %}
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-3">
                                <img src="{{ item.image.url }}" class="cartImage" alt="zdjecie">
                            </div>
                            <div class="col-6"><p>{{ item.name }}</p></div>
                            <div class="col-3"><p>{{ item.price }}</p></div>
                        </div>
                        <button type="button" class="btn btn-primary addToCart my-2" data-bs-toggle="modal"
                                data-bs-target="#exampleModal"
                                data-id="{{ item.id }}">Add to Cart
                        </button>
                        <a data-id="{{ item.id }}" class="btn btn-danger btn-sm deleteFavorite">
                            <i class="fa fa-times">Delete</i>
                        </a>
                    </div>
                {% endfor %}
            {% else %}
                <h1 class="text-center">No favorite listings</h1>
            {% endif %}

        </div>
    </div>


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Dodano do koszyka</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                    <a href="{% url 'listings:cart' %}" type="button" class="btn btn-secondary"
                       data-bs-dismiss="modal">Wroc do zakupow
                    </a>
                    <a href="{% url 'listings:cart' %}" type="button" class="btn btn-primary">Idz do koszyka</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/accounts/information.html
{% extends 'base.html' %} {% load static %} {% block content %}{% load crispy_forms_tags %}

    <div class="container py-5">
        <table class="table">
            <thead>
            <tr>
                <th>Info</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td scope="row"></td>
                <td>Username:</td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td scope="row"></td>
                <td>Account Level:</td>
                {% if user.is_staff %}
                    <td>Admin</td>
                {% else %}
                    <td>User</td>
                {% endif %}
            </tr>
            <tr>
                <td scope="row"></td>
                <td>Created:</td>
                <td>{{ user.date_joined }}</td>
            </tr>
            <tr>
                <td scope="row"></td>
                <td>Favorite:</td>
                <td><a href="{% url 'accounts:favorite' %}">Link</a></td>
            </tr>
            </tbody>
        </table>
        <a name="Logout" class="btn btn-primary" href="{% url 'accounts:logout' %}" role="button">Log out</a>
        {% if user.is_staff %}
            <a name="Logout" class="btn btn-primary" href="{% url 'admin:index' %}" role="button">Go to admin page</a>
        {% endif %}
    </div>
{% endblock %}

shop/templates/accounts/loggedout.html
{% extends 'base.html' %} {% load static %} {% block content %}{% load crispy_forms_tags %}

<div class="container-fluid py-5">
	<p class="fa text-center" aria-hidden="true">User logged out.</p>
</div>
{% endblock %}

shop/templates/accounts/login.html
{% extends 'base.html' %} {% load static %} {% block content %}{% load crispy_forms_tags %}

    <div class="container py-5">
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %} {{ login_form|crispy }}
            <button class="btn btn-primary" type="submit">Login</button>
        </form>
        <p class="text-center">Don't have an account? <a href="{% url 'accounts:register' %}">Create an account</a>.</p>
    </div>
{% endblock %}

shop/templates/accounts/register.html
{% extends 'base.html' %} {% load static %} {% block content %} {% load crispy_forms_tags %}

<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %} {{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'accounts:login' %}">login</a> instead.</p>
</div>

{% endblock %}