shop/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_request, name='login'),
    path('register/', views.register_request, name="register"),
    path('information/', views.account_info, name="acc_info"),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='accounts/loggedout.html',
    ), name="logout"),
    path('favorite/', views.favoriteListings, name="favorite"),
    path('deleteFavorite/', views.deleteFavorite, name="deleteFavorite"),
    path('addFavorite/', views.addFavorite, name="addFavorite"),
]

shop/listings/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.index, name='index'),
    path('listings/<int:id>', views.listing, name='listing'),
    path('search/', views.search, name="search_results"),
    path('quicksearch/', views.quick_search, name="quick_search"),
    path('category/<int:id>', views.category, name="category"),
    path('updateCart/', views.update_cart_item, name="update_cart_item"),
    path('cart/', views.cart_view, name="cart"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('listings.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('checkout/', include('checkout.urls')),
]

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Great Shopping experience</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/css.css' %}"/>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a href="{% url 'listings:index' %}"><img src="{% static 'img/logo.png' %}" width="107" height="54" alt=""
                                                  class="navbar-brand" href="{% url 'listings:index' %}"/></a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active mr-5" aria-current="page" href="{% url 'listings:index' %}">Home</a>
                <form class="d-flex dropdown" action="{% url 'listings:search_results' %}" method="get"
                      autocomplete="off">
                    {% csrf_token %}
                    <input class="form-control me-2 dropdown-toggle" type="text" id="quicksearch" placeholder="Search"
                           aria-label="Search" name="q" data-bs-toggle="dropdown" aria-expanded="false"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                    <ul class="dropdown-menu" id="searches" aria-labelledby="dropdownMenuLink">
                        <li><p class="dropdown-item disabled">Ostatnio wyszukiwane</p></li>
                        {% for search in request.session.lastSearch %}
                            <li><a class="dropdown-item"
                                   href=" {% url 'listings:search_results' %}?q={{ search }} ">{{ search }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </form>
            </div>
        </div>
        <a href="{% url 'listings:cart' %}" class="float-right"><img src="{% static 'img/cart.png' %}"
                                                                     alt="Koszyk" width="30px"
                                                                     height="30px"></a>
        {% if not user.is_authenticated %}
            <a class="nav-link active mr-5 btn- ms-auto" href="{% url 'accounts:login' %}">Log In</a>
        {% else %}
            <a class="nav-link mr-5 ms-auto" href="{% url 'accounts:acc_info' %}">{{ user.username }}</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% block content %} {% endblock %}
<footer class="text-center bg-light container-">
    <p>Prawa reserved</p>
</footer>
<script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/quicksearch.js' %}"></script>
<script src="{% static 'js/cart.js' %}"></script>
<script src="{% static 'js/paymentCheckout.js' %}"></script>
</body>
</html>